### ISSUE TITLE
[JOSS Review] Documentation in development stage, does not answer key questions

### ISSUE THREAD

**Issue by villaa** [SotaYoshida/NuclearToolkit.jl#32]
The documentation [here](https://sotayoshida.github.io/NuclearToolkit.jl/dev/) does not seem to be quite complete. I have had problems installing and running the simplest example--those I will address in a separate GH issue--but the documentation does not include some of the information that the paper does, like "statement of need" and others that are required by the review criteria like:

- automated tests
- community guidelines 

I always use this [excellently documented code](https://github.com/temken/obscura) published in JOSS as an example. In that case, automated tests are completed through GitHub Actions. For a community guidelines example please see [my code](https://github.com/villano-lab/nrCascadeSim) under the file `CONTRIBUTING.md`

**Comment by villaa** [comment]
I now see the paragraph:

> [Issues/Pull requests](https://sotayoshida.github.io/NuclearToolkit.jl/dev/#Issues/Pull-requests)
> 
> NuclearToolkit.jl is designed to be an open-source software and to guarantee reproducibility and transparancy of the future works. Making issues and pull requests are fully welcome. If you would like to contribute to development of the package and want be an author of future versions of the paper, please do not hesitate to contact me (S.Yoshida).

In the documentation. This is similar to the `CONTRIBUTING.md` that I mentioned but lacks some things that are preferable to have:

- workflow (which branches to submit PR to, etc)
- code style
- code of conduct; this is actually in `CODE_OF_CONDUCT.md` file of the example repository.

**Comment by SotaYoshida** [comment]
@villaa 
Thank you so much for giving me very helpful suggestions and excellent examples to follow.
I will look through these and make modifications to the package.

**Comment by SotaYoshida** [comment]
@villaa Thanks again. I have made some modifications on the document, [dev](https://sotayoshida.github.io/NuclearToolkit.jl/dev/).

Since I am new to JOSS, I have something I would like to ask you:
1. > the documentation does not include some of the information that the paper does, like "statement of need" 

    I was thinking the [Package features](https://sotayoshida.github.io/NuclearToolkit.jl/dev/#Package-features) section in the document corresponds to "statement of need". Do I need the 'Statement of Needs' section in the document exactly like the paper?
2. I added a new page [Contributing to NuclearToolkit.jl](https://sotayoshida.github.io/NuclearToolkit.jl/dev/contributing/#Contributing-to-NuclearToolkit.jl) in the document explaining workflow of development, automated tests with JuliaTagBot and GitHub Actions, and "community guideline" stuffs.

To make the document better, I would be grateful if you could tell me whether what is required for review process is "roughly" met by what I added.

**Comment by villaa** [comment]
Ok, in that case I think the documentation is good and I'll close this issue. #33 has another issue within it that is related to documentation, but beyond the scope of this issue. There it is about documenting the expected output from the example commands.
