### ISSUE TITLE
[JOSS REVIEW] IO errors when running with MPI

### ISSUE THREAD

**Issue by mdavezac** [SotaYoshida/NuclearToolkit.jl#38]
When running with mpi and multiple processors, I get the following errors:

1. Anything printed to the stdout is printed identically multiple times
1. At the very end, after printing the results, an error occurs:
   > SystemError: opening file "flowOmega/Omega_21970O16_1.bin": No such file or directory

The first error certainly is a result of printing outputs from all processes, rather than from the main process only. Perhaps some `verbose` variable can be set to `false` for other processes other than main?

I guess the second error also comes from trying to write from all processes. However, if the information written to the binary files is not the same on all procs, it might be more complicated to correct.

Part of openjournals/joss-reviews#4694.

**Comment by mdavezac** [comment]
For the record, 1. is an annoyance but it shouldn't hold back publication. However, I would think 2 affects the functionality and usability of the code and should be required to claim that the code works with MPI.

**Comment by SotaYoshida** [comment]
@mdavezac Thank you again!

In summary, this issue may not be on the code, but the document. Let me try to explain.

From the error message,
> SystemError: opening file "flowOmega/Omega_21970O16_1.bin": No such file or directory

you may have run in-medium SRG (IM-SRG) calculations with MPI.
The error is due to the [function](https://github.com/SotaYoshida/NuclearToolkit.jl/blob/main/src/IMSRG.jl/imsrg_util.jl#L638) to clean previous temporary files `flowOmega/*`, which are generated through solving matrix ODEs repeatedly.

>For the record, 1. is an annoyance but it shouldn't hold back publication. However, I would think 2 affects the functionality and usability of the code and should be required to claim that the code works with MPI.

I am afraid to say... in the first place, I am not claiming one can benefit from multi-node parallelization (using e.g. MPI.jl) for many-body methods in the package.
In this package, the MPI is used explicitly only for MCMC samplings using HF-MBPT (one many-body method) and affine-invariant MCMC, which is a kind of ensemble method that uses the results of independent runs to make MCMC sampling efficient.

My intent 
- in the paper 
    > ... works on both laptops and supercomputers in almost the same way.
- in the document
    >  The code can be easily executed on either a laptop or a supercomputer. 

was... one can easily run the code on different environments due to Julia's Pkg manager and portability, and I did not mean to say one can benefit from MPI elsewhere.

Sorry for the confusion.
I will improve the document for both #38 and #39.

**Comment by mdavezac** [comment]
Okay, thanks for clearing that up. I misunderstood the claim "works on supercomputers" as "works with MPI". To be fair, that might be a common misunderstanding :). Perhaps it would be a good idea to document where MPI is expected to work explicitly.

A suggestion: Have you tested this on Windows? Perhaps the same idea can be conveyed by saying "works on a variety of environments, including Mac, linux, and Windows"? This shouldn't result in fewer understanding about hardware.

**Comment by SotaYoshida** [comment]
> To be fair, that might be a common misunderstanding :)

You're absolutely right. 

>A suggestion: Have you tested this on Windows? Perhaps the same idea can be conveyed by saying "works on a variety of environments, including Mac, linux, and Windows"? This shouldn't result in fewer understanding about hardware.

Not actually. I added the test through GitHub Actions on Windows, and the code works fine.

I will make a pull request and the updated document will be available soon.
I would appreciate it if you could take a look through it.
