### ISSUE TITLE
[JOSS Review] tbme_fmt="snt"

### ISSUE THREAD

**Issue by mdavezac** [SotaYoshida/NuclearToolkit.jl#39]
If I understand correctly, this should create a text file rather than a binary file.
However, it doesn't seem to work. It still creates an binary file.

**Comment by SotaYoshida** [comment]
@mdavezac Thanks.

Actually, it depends on which output you are talking about.
The optional argument `tbme_fmt` is the option not for "valence-space" interaction (output of many-body method), but for "free-space" interaction (output of src/chiEFTint stuff).

Taking a [test code](https://github.com/SotaYoshida/NuclearToolkit.jl/blob/main/test/runtests.jl) as an example:

```julia 
L7: @test make_chiEFTint(;fn_params="optional_parameters.jl")
L8: @test make_chiEFTint(;fn_params="optional_parameters_snt.jl")
```
L7 &L8 write out the same nucleon-nucleon force matrix elements in snt.bin(binary) and snt(text) format, respectively.

Then, we check to see whether or not we can get the same results of HF-MBPT calculation with them
```julia
L18: HFobj1 = hf_main(nucs,sntf,hw,emax;return_obj=true)
L30: tsntf = replace(sntf,".snt.bin" => ".snt")
L31: HFobj2 = hf_main(nucs,tsntf,hw,emax;return_obj=true)
```

After that, another many-body method, valence-space IMSRG, is called through `hf_main` API
```julia
L42: hf_main(nucs,sntf,hw,emax;doIMSRG=true,corenuc=core,ref="nuc",valencespace=vspace,return_obj=true)
```
This generates an effective Hamiltonian for a specified valence space, which are always in ".snt"(text) format.
These effective interactions are used for the so-called shell-model calculations, 
Since the valence-space interactions are typically not large file and snt format is used in the popular shell-model code, one may not need to make it binary form.

The option seems to work properly, but I understand I need to improve the document.
Thank you for your feedbacks.

**Comment by mdavezac** [comment]
Thanks. That clears that up.

On the other hand, unless I missed it, it's the meaning and format of the "flowOmega/*.bin" is not stated in the docs. If they are just for internal usage, that's okay.

**Comment by SotaYoshida** [comment]
>On the other hand, unless I missed it, it's the meaning and format of the "flowOmega/*.bin" is not stated in the docs. If they are just for internal usage, that's okay.

These are just for temporary files, but I added the explanation to [IMSRG page of the document](https://sotayoshida.github.io/NuclearToolkit.jl/dev/IMSRG/#IMSRG) future possible development by me or others. Thanks.
